### ISSUE TITLE
Call service remains open when the application is closed

### ISSUE THREAD

**Issue by AlexeyOvchynnikov** [Azure/communication-ui-library-android#1022]
**Describe the bug**
It's not possible to close the call service (`InCallService`) together with the app. The calling service continues to work when the application is closed by swiping from recent applications.

**To Reproduce**
1. Add [communication-ui-library-android](https://github.com/Azure/communication-ui-library-android/tree/main/azure-communication-ui/calling) to your app ([demo-app](https://github.com/Azure/communication-ui-library-android/tree/main/azure-communication-ui/demo-app) can be used as well)
2. Override `android:stopWithTask` value to `true` in AndroidManifest.xml for `com.azure.android.communication.ui.calling.service.InCallService`:
```
<service
	tools:replace="android:stopWithTask"
	android:name="com.azure.android.communication.ui.calling.service.InCallService"
	android:foregroundServiceType="microphone"
	android:stopWithTask="true"
	android:exported="false" />
```
4. Run the app
5. Start call
6. Open recent apps.
7. Kill the application

**Expected behavior**
The call process closes along with the app

**Screenshots**
![Screenshot_20240619-124246_One UI Home](https://github.com/Azure/communication-ui-library-android/assets/29628029/ac2aebf7-395a-459c-adf3-45591b1e2feb)
![Screenshot_20240619-124316_One UI Home](https://github.com/Azure/communication-ui-library-android/assets/29628029/df336322-cede-426f-8edc-d77427b62b66)

**AzureCommunicationUILibrary (please complete the following information):**
 - Version 1.8.0-beta.1

**Smartphone (please complete the following information):**
 - Device:  Samsung Galaxy M11
 - API: API31

**Additional context**
Reproduces on any device

**Comment by pavelprystinka** [comment]
Hi @AlexeyOvchynnikov,

Thanks for your inquiry.

I guess you have enabled a multitasking on the CallComposite. Then this is an expected behaviour. In this case activity life should not affect call service, as when switching to Picture-in-picture and back activity is finished and only service keeps 
App process alive. This is the way most calling App are done on the Android, you may also compare behaviour with Teams.

Thank you.

**Comment by mithileshbhumca** [comment]
@pavelprystinka  This same issue happening on my integration also, can you check below bug 
#1170 
#1177
