### ISSUE TITLE
RuntineException when targeting Android 12

### ISSUE THREAD

**Issue by juaram2** [Azure/communication-ui-library-android#140]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Start call

### Any log messages given by the failure
>Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable
![image](https://user-images.githubusercontent.com/26706369/159225644-5e67fc8d-690f-4e79-b15c-a3fa27f687bb.png)

### Expected/desired behavior
> Start call on Android 12

### OS and Version?
> Android 12

### Versions
> 1.0.0-beta.1

### Mention any other details that might be useful

https://developer.android.com/about/versions/12/behavior-changes-12#unsafe-intent-launches

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by iaulakh** [comment]
Hi @juaram2, This issue has been fixed on branch `develop/beta` [PR](https://github.com/Azure/communication-ui-library-android/commit/5b74d1762812814831cbf50b2d0e048f43d3835e) . Would it be possible for you to try `develop/beta` branch until we release a new version(soon)?

**Comment by iaulakh** [comment]
Hi @juaram2, please let me know if the PR fix works fine. We can investigate further if issue is not fixed by PR :)

**Comment by juaram2** [comment]
> Hi @juaram2, please let me know if the PR fix works fine. We can investigate further if issue is not fixed by PR :)

It's working well. I hope the new release comes out soon.

**Comment by iaulakh** [comment]
@juaram2 please try with latest release 
`implementation 'com.azure.android:azure-communication-ui:1.0.0-beta.3'`
