### ISSUE TITLE
Join with an ID

### ISSUE THREAD

**Issue by haohighview** [Azure/communication-ui-library-android#380]
![image](https://user-images.githubusercontent.com/8456671/182071740-063949bf-9560-4991-8d31-6ea6a9048a3e.png)
Can we support joining a meeting by ID?

**Comment by iaulakh** [comment]
@haohighview  we appreciate the feedback. Currently, UI libraries supports joining call with `meeting link`.
To help look into the issue further could you please provide some additional information about the use case(need to join meeting with ID)?

**Comment by haohighview** [comment]
![image](https://user-images.githubusercontent.com/8456671/182506610-a01aa24d-1eda-44f6-abda-039e6d17c1fc.png)
Now created teams meeting will generate meeting id and password. You can join the meeting by entering the id and password.

**Comment by garchiro7** [comment]
Hi @haohighview, thank you for the suggestion; it would be an excellent opportunity to improve the libraries. I encourage you to share your ideas here in the [Azure Share Ideas forum.](https://feedback.azure.com/d365community/forum/81ff6d2b-0c25-ec11-b6e6-000d3a4f0858)

We actively look for improvements and valuable feedback here.

**Comment by garchiro7** [comment]
Please vote for this idea:

https://feedback.azure.com/d365community/idea/2b504160-5513-ed11-a81b-6045bd8606d4

**Comment by iaulakh** [comment]
Hi @haohighview, https://feedback.azure.com/d365community/idea/2b504160-5513-ed11-a81b-6045bd8606d4 is created as per discussion. 

Please reopen issue, if more information is required.
