### ISSUE TITLE
Does it support external cameras?

### ISSUE THREAD

**Issue by haohighview** [Azure/communication-ui-library-android#384]
Does it support external cameras? Thanks!

**Comment by Mrayyan** [comment]
Hi @haohighview,

We do not support external  cameras at the moment. There has been no testing done regarding external cameras so far.

**Comment by haohighview** [comment]
Android TV

**Comment by iaulakh** [comment]
Hi @haohighview,

would it be possible for you to have a discussion with our team about the use cases that you are working on? During discussion:
We can make a note of use cases that you are working on and can discuss with our team to see if we can bring few more features into product :)

**Comment by haohighview** [comment]
The device our app runs on does not have a built-in camera. After adding an external camera to the device, the app cannot recognize it. Unable to turn on camera.

**Comment by iaulakh** [comment]
Hi @haohighview,
 
In future, we are planning to expose API to support raw media access. The API will help to use any camera for streaming. We will let you know once this feature will be implemented.

We are dependent on https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-with-video-calling?pivots=platform-android. The latest feature https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-raw-media-access?pivots=platform-android will help for streaming any camera feed.

**Comment by iaulakh** [comment]
Hi @haohighview,

Please create idea at https://feedback.azure.com/d365community/forum/81ff6d2b-0c25-ec11-b6e6-000d3a4f0858.
