### ISSUE TITLE
Add support for rooms

### ISSUE THREAD

**Issue by chaosifier** [Azure/communication-ui-library-android#446]
Can we support feature to join rooms?

[Quickstart on Joining Rooms](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/rooms/join-rooms-call?pivots=platform-android)

**Comment by iaulakh** [comment]
Hi Sagar, thanks for reaching out. The current plan for ACS UI SDK to integrate with the Rooms SDK is currently planned for 2023. 

Is there a particular feature from the Rooms SDK that you or your team is looking to utilize via the UI SDK? We can ensure we add your feature ask as part of UI SDK development requirements, and if the feature is currently not available in the Rooms SDK (Public Preview), we can make a request to the Rooms SDK team as they finalize the Rooms SDK for General Availability.

Again, thank you for your interest and I look forward to hearing your feedback!

**Comment by chaosifier** [comment]
For the moment, just getting access to base APIs related to Rooms on Android and iOS would be enough. 
As I have mentioned [here](https://github.com/MicrosoftDocs/azure-docs/issues/98990#issuecomment-1258885542), the documentation shows the use of RoomCallLocator in Android and iOS to join Rooms, but the API seems to be nowhere. It would be great if you could lead me to the libraries used in the documentation.

**Comment by iaulakh** [comment]
@chaosifier please reopen if you need more info.
