### ISSUE TITLE
Add Call Over to startCallComposite

### ISSUE THREAD

**Issue by cheymonty** [Azure/communication-ui-library-android#709]
What feature are you requesting?
After creating the composite, there should be a way to know when the composite is closed (due to the meeting ending for all or the user leaving themselves)

What would be the benefit of adding this feature?
The app will be able to know when the call is over

What solution would be ideal for you?
a callback parameter or return value

What alternatives have you considered?
There are no alternatives

**Comment by ahammer** [comment]
Since the Call Composite is an activity can you use the activity life cycle for your use-case at the moment (we will discuss adding  soon).

I.e. 
CallComposite.launch(...)
YourActivity->onPaused
CallComposite->onStart
CallComposite->onDestroy
YourActivity->onResumed

If you save in your activity that you are launching a composite, when you return to it (i.e. it's resumed) it can be assumed that the call has ended?

**Comment by Mohtasim** [comment]
Hi @cheymonty,
Thanks for your feature request. Currently our composite does not have the capability of what you are asking. We'll put your request in our backlog for further review and prioritization. Meanwhile for Android native you can try out the workaround suggested above.

But if it is an urgent requirement for your business need, our library is open source and you are most welcome to contribute around your feature request with a pull request. We'll review your contribution and help you through the process to get you the UI Library build.
Please follow our [contribution guideline](https://github.com/Azure/communication-ui-library-ios/blob/main/docs/contributing-guide.md) if you wanted to contribute around the feature.

**Comment by Mohtasim** [comment]
Re-opening this issue to track the feature request progress and providing further feedbacks regarding the request. 
Thanks.

**Comment by pavelprystinka** [comment]
@cheymonty 

This feature was added in the 1.4.0 version. Please see this [tutorial](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/ui-library/get-started-composites?tabs=kotlin&pivots=platform-android#dismiss-callcomposite-and-subscribe-to-dismissed-event)
