### ISSUE TITLE
Bypassing the Setup screen and  "Join Call" button and immediately start the call

### ISSUE THREAD

**Issue by kungbernard** [Azure/communication-ui-library-android#733]
**What feature are you requesting?**
Currently before entering to the meeting, user need to click on the "Join Call" button in the setup screen (attached). Would be great to allow settings (such as video on/off, microphone on/off) to be added as properties to start the call immediately without needing to press the "Join Call" button.

**What would be the benefit of adding this feature?**
By allowing user to go directly to the meeting without pressing the "Join Call" button, we can create a high priority push notification that has the "Answer" action and go directly to the meeting, this will provider better user experience than having an extra step to press the "Join Call" button before entering the meeting. 

**What solution would be ideal for you?**
Allowing user to go directly to the meeting.

**What alternatives have you considered?**
N/A

**Is there any additional information for your request?**
![IMG_8485](https://user-images.githubusercontent.com/15023090/229434974-ba9e88b8-4e73-4ae5-b387-15f1dd0c74bc.PNG)

**Attach screenshots or images add detail to your request:**

**Comment by ShaunaSong** [comment]
Hi @kungbernard, thank you for reaching out.
We have introduced a skip setup screen with the call configuration API for an improved initial call join experience in our latest release.

Please refer to our newest release on GitHub: https://github.com/Azure/communication-ui-library-android/releases/tag/calling-v1.3.0 for more information.
You can access this feature using the `CallCompositeLocalOption` class.

**Comment by Mohtasim** [comment]
Hi @kungbernard, please refer to the [doc](https://learn.microsoft.com/en-us/azure/communication-services/how-tos/ui-library-sdk/skip-setup-screen?tabs=kotlin&pivots=platform-android ) to get more clarification should you need more.

**Comment by kungbernard** [comment]
Thanks @ShaunaSong  and @Mohtasim 
Great to see the feature is being introduced in so short period of time!
