### ISSUE TITLE
Image send and receive in chat, Invite new person

### ISSUE THREAD

**Issue by androidgopi** [Azure/communication-ui-library-android#789]
Here we have some queries while development.

1.	In the mobile app chat,  when we send an image from the web client, app is receiving an image with meta-data value(ex.,["0- 
        sa-d6-c88d2de5e0b06c63fdda74f222ada9ed","0-sa-d6-c88d2de5e0b06c63fdda74f222ada9ed"]) in ChatMessage class. How to 
        download an image with this meta-data and how to show the same image in chat?

2.	How to send an image in chat from the app?

3.	How to Invite another VoIP participant to join in an ongoing group call?

We didn't find any APIs or any documented details for the above requirements, could you please help us with these items on how to achieve these?

**Comment by iaulakh** [comment]
Hi @androidgopi,

Thank you for opening an issue. Would it be possible to provide the following information:

- Are you using calling and chat UI libraries together for your project?

- Regarding the statement "when we send an image from the web client," could you please share more information about the client? Are you referring to the Teams Client or the Web ACS UI Library?

- With regards to the question "How to invite another VoIP participant to join an ongoing group call?", are you referring to sending a notification when one participant starts a call?

Please let me know if you need any further clarification.

**Comment by androidgopi** [comment]
Hi @iaulakh,

Thanks for the quick response,

- **Are you using calling and chat UI libraries together for your project?**
Yes we are using call and chat UI libraries.

- **Regarding the statement "when we send an image from the web client," could you please share more information about the client? Are you referring to the Teams Client or the Web ACS UI Library?**
 Web client means Microsoft Desktop Teams app. Actually, we are trying to send and receive the images over the chat, for that we are using **ChatUI libraries** in Android.  But we didn't find any info on how to send or receive images. Is there any API or document reference for that? it will help us a lot.


- **With regards to the question "How to invite another VoIP participant to join an ongoing group call?", are you referring to sending a notification when one participant starts a call?**
 No, we are not referring that. Like the Microsoft Desktop Teams app, how users are getting invite into the current ongoing call, like the same we want in integrated teams SDK also. (Eg., User1, User2, User3 is already there in call, now how to invite User4 into the same call?)

**Comment by iaulakh** [comment]
Hi @androidgopi,

Thank you for the follow-up.

Currently, the ChatWithChat UI libraries are in prototype and have not been officially released on Maven and CocoaPod. Here are the available libraries:
- Call: [Android](https://search.maven.org/artifact/com.azure.android/azure-communication-ui-calling), [iOS](https://github.com/Azure/communication-ui-library-ios/releases)
- Chat: [Android](https://search.maven.org/artifact/com.azure.android/azure-communication-ui-chat), [iOS](https://github.com/Azure/communication-ui-library-ios/releases)
- CallWithChat: This library is still in the prototype stage.

The only way to add a participant through the UI library is by sharing the group call GUID, which allows participants to join. You can utilize the [Quickstart - Handle voice and video calling events - An Azure Communication Services quickstart | Microsoft Learn](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/handle-calling-events) or your own push notification mechanism to send notifications to other participants. Currently, inviting other participants through the UI library is not supported but is on the roadmap. However, the native calling SDKs [link](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/getting-started-with-calling?tabs=uwp&pivots=platform-android) do support adding participants.
Calling Native UI SDK depends on Calling Native SDK, and that for developers who needs more configurability and customization, they can choose to integrate with Calling Native SDK instead (no UI provided). For Calling Native SDK, the functionality of adding participants API is available.

At this time, we only support in the web UI Library for chat for Teams interop scenario to receive image, you can find the documentation here: https://learn.microsoft.com/en-us/azure/communication-services/tutorials/chat-interop/meeting-interop-features-inline-image but sending image from ACS Mobile UI Library is not support at the moment.

Please let us know if you need more information.
