### ISSUE TITLE
cant use  User Facing Diagnostics in all versions

### ISSUE THREAD

**Issue by AhmedKhattab95** [Azure/communication-ui-library-android#825]
**Bug Description**
I am seeking improved documentation for utilizing [User Facing Diagnostics](https://learn.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/user-facing-diagnostics?pivots=platform-android) in Android and iOS using the current SDK. When attempting to implement the provided code, I encounter issues where certain classes are not found.

java  code
```
DiagnosticsCallFeature diagnosticsCallFeature = call.feature(Features.LOCAL_USER_DIAGNOSTICS);
NetworkDiagnostics networkDiagnostics = diagnosticsCallFeature.getNetwork();
MediaDiagnostics mediaDiagnostics = diagnosticsCallFeature.getMedia();

NetworkDiagnosticValues latestNetwork = networkDiagnostics.getLatestDiagnostics();
Boolean lastNetworkValue = latestNetwork.isNetworkUnavailable();
DiagnosticQuality lastReceiveQualityValue = latestNetwork.getNetworkReceiveQuality();

MediaDiagnosticValues latestMedia = networkDiagnostics.getLatestDiagnostics();
Boolean lastSpeakerNotFunctionValue = latestMedia.isSpeakerNotFunctioning();

```
**Steps to Reproduce**

Install the SDK by following the steps [here](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/ui-library/get-started-composites?tabs=java&pivots=platform-android) which works as expected.
Attempt to implement the provided code, resulting in missing class imports and non-functional code. It appears that this functionality might not have been implemented yet in the SDK.

**Questions**

Is this functionality available in the client SDKs for Android and iOS?
Can this be accessed through external APIs for API integration?
Expected Behavior
I expect that all the provided code should work smoothly and allow for proper class imports.

**Additional Information:**

AzureCommunicationUILibrary Version: implementation 'com.azure.android:azure-communication-ui-calling:+'
Smartphone Device: All devices
Please let me know if the mentioned functionality is present in the client SDKs for Android and iOS, or if it's accessible through external APIs. The code provided should ideally work without any issues. Thank you.

**Comment by ahammer** [comment]
Thank you for reaching out with your concerns related to the User Facing Diagnostics (UFD) feature.

I understand that you are trying to utilize the UFD feature in the UI SDK but are encountering problems with missing classes and non-functional code.

Availability in Client SDKs: The User Facing Diagnostics (UFD) feature is a part of our Headless Native Calling SDK. We are in the process of integrating it into the Azure Communication Services UI Library (UI Composites). The UFD will integrate seamlessly into the call screen to provide users with feedback on call issues. Our current projection is for it to be included in an upcoming release scheduled for late October. The UI library integration is not expected to require any API's or configuration to utilize the feature.
Access through External APIs: Currently, the UFD is designed to be leveraged directly through the headless Client SDK, and there's no external API endpoint to access these diagnostics.

Please monitor Releases of the Calling UI Library to see when the feature will be implemented in the composites.

We sincerely apologize for any previous inconvenience. We greatly appreciate your feedback and it plays a pivotal role in our ongoing efforts to improve the SDK.

Thank you for your patience and understanding.
