### ISSUE TITLE
Screen Sharing feature now working

### ISSUE THREAD

**Issue by pkdhankher** [Azure/communication-ui-library-android#890]
**Describe the bug**
This ticket is not for a bug report. I'm trying to add Azure Communication SDK to my Android app. Calling is working fine but I can't find any documentation related to Screen Sharing. Can you guys share some insites that how can I implement Screen sharing in my app? 

Is it even possible with the Android SDK?

**Comment by pkdhankher** [comment]
https://learn.microsoft.com/en-us/azure/communication-services/concepts/voice-video-calling/calling-sdk-features#detailed-capabilities

**Comment by iaulakh** [comment]
Hi @pkdhankher , 

Thank you for opening the issue. It looks like you were able to figure out a solution. Please reopen it if necessary.
