### ISSUE TITLE
Call composite closes but call is still ongoing

### ISSUE THREAD

**Issue by cheymonty** [Azure/communication-ui-library-android#999]
**Describe the bug**
I am using this library inside React Native, and am seeing an issue with the `CallComposite.dismiss()` function. I have a push notification that, when received, calls `dismiss()` but when the app is in the background and moved to foreground by pressing the notification, the composite is dismissed, but the android os still says the call is active. I believe this is due to having two activities open, but was wondering if there could be someway to completely kill the call. I did some digging and found `CallingAction.CallEndRequested()` in the `exit()` function. Maybe a boolean to pass that kills the call? I can work on the fix if there is some guidance on the best course of action.

**To Reproduce**
1. With two activities open, and acs being the one on top, make the `launch()` call from the bottom activity and add a timer that x seconds after launching the composite, `dismiss()` is called
2. Send app to background (not killed)
3. Open app: The composite will close but the os will show that the call is still ongoing
4. This bug is [always] reproducible. 

**Expected behavior**
The composite is closed and the os does not say the call is ongoing

**Screenshots**
![os](https://github.com/Azure/communication-ui-library-android/assets/45781686/d7508b93-7aa4-4d37-a4fb-d32be47f91aa)

**AzureCommunicationUILibrary (please complete the following information):**
 - Version [1.4.0]

**Smartphone (please complete the following information):**
 - Device: [Pixel 4a]
 - API: [33]

**Comment by Mohtasim** [comment]
Hi @cheymonty,

May I suggest that please feel free to use our latest released publicly available version 1.6.1 of AzureCommunicationUILibrary.

We could not reproduce the reported issue on our latest released version. 

Thank you.
